### ISSUE TITLE
NFC->Beacon 수정 

### ISSUE THREAD

**Issue by tksrl0379** [tksrl0379/OutOfKiosk#17]
<del>
NFC 기능 추가

-Stopped
현재 NFC 리더기가 아이폰에 적용하기 어려운 점이 있어 이를위해 여러 상점과 컨택중.
 TTCNC 회사 http://www.ttcnc.co.kr/connectivity-main/nfc-module/
070-8226-1006 

Tag write 시에 현재 개발한 어플은 writable과 memory size가 보이지 않는다. (이 부분을 해결해야함.)
BuildingAnNFCTagReaderApp 참조해서 다시 어플만들기.

-Done
App을 만들어서 Data를 NFC 스티커에 장착시키는 것 완료.

</del>

---

2/13
NFC 및 QR코드는 공통적으로 시각장애인이 리더기의 정확한 위치를 알고 있어야 사용 가능하다는 단점을 가지고 있다. 따라서 NFC가 아닌 beacon을 이용하여 시각 장애인이 beacon의 사정거리에 들어오는 순간 바로 주문이 가능하도록 아이디어를 변경하였다. 

- Issue
Apple에서는 ibeacon을 찾아 그 비콘의 식별자(UUID/Major/Minor)를 찾는 Method를 제공하지 않고, 위약에 걸릴 수 있다고 명시해 놓았다. 하지만 하드코딩을 통해 감지된 비콘의 식별자를 알 수 있는 어플이 있으며 이는 가능성은 있으나 난이도가 object-c 버젼이라 swift버전으로 교환하기에는 시간이 걸릴 것으로 보인다.

두가지 시나리오를 염두해 두어야한다.
1. 비콘의 식별자를 미리 입력하여 식별된 비콘이 탐지될 경우 장바구니 아이템이 전송되는 과정.
2. 비콘이 탐지되면 해당하는 식별자가 무엇인지를 확인하는 방법.

먼저 1번을 하여 비콘을 통한 주문을 시도해 본 후, 완료가 되면 2번방법을 구현해 보도록 한다.

- Todo

-Done
비콘 테스트 프로젝트 만들기.
Monitorring이 되어서 핸드폰 백그라운드에서 작동이 되는지 확인하기
비콘이 탐지되면 장바구니에 있는 아이템이 AWS 서버 디비테이블로 넘어가게한다.
현재 장바구니에서 비콘주문 시, 비콘이 탐지가 될 경우 백그라운드(앱을 나간상태)에서도 주문이 가능하다.
(하지만 백그라운드에 한계 시간이 존재한다.-> IOS App Cycle의 한계 
**30sec. Apple 정책** -> 그렇다면 카톡같은 경우는 어떻게? Notification을 이용한 background 깨우기?)
Background Time을 설정하여 App이 suspend된 상태에서도 메소드를 구현 할 수 있도록 하기.
https://www.raywenderlich.com/5817-background-modes-tutorial-getting-started
Background time limit 측정하기
->실제로 30분정도의 시간을 두고 비콘탐색에서 background의 리밋한계가 보이질 않았다.
비콘주문 -> on/Off 설정하기.
shoppingList에서 나가면 비콘탐지기능을 끄는 기능 필요.(cpu점유율에 문제)

**Comment by JacksonPk** [comment]
NFC Tag 쓰기
1. Target -> Signing & Capability에 들어가서 + 버튼을 누른 후 Near Filed Communication등록.
2. Info.plist에 들어가서 등록
    1. Privacy - NFC Scan Usage Description
3. AppDelegate 등록 딱히 필요 없음.
4. 

NFC Tag 읽기
1. Target -> Signing & Capability에 들어가서 + 버튼을 누른 후 Near Filed Communication등록.
2. Info.plist에 들어가서 등록
    1. Privacy - NFC Scan Usage Description 
    2. ISO7816 application identifiers for NFC Tag Reader Session
    3. ISO18092 system codes for NFC Tag Reader Session
3. AppDelegate에 등록할 부분이 필요.


Delegate 설정 시,
NFCTagReaderSession (X)
NFCNDEFReaderSession (O)
이유는 잘 모르겠으나, NDEF로 해야 실제 페이로드가 잘 들어간다.

Text DATA를 넣고 싶을때

self.message.records[2].payload = "\u{02}enHELLO".data(using: .utf8)!

여기서 \u{02}en 이 핵심이다. 
NFC Tag에 여러종류에 Data prefix가 존재하는데  예를 들어서
1. \u{02}en 은 payload.wellKnownTypeTextPayload().0! 에 해당하는 Text형식.
2. \u{05} 는 Tel(전화번호) 형식.
3. \u{04} 는 URI 형식이다.

각각의 형식이 존재하며 또한, 형식이 다른점에 대비하여 Tag Scan시 맞는 형식으로 get해야한다.

추측이지만 전화번호 119를 TextPayload로 읽을때와 URIPayload로 읽을 때 차이는
Text는 그냥 119라는 숫자만 읽고 URI로 받으면 클릭 시, 핸드폰 내장API로 전화를 직접 걸 수 있을 것이다.

비어있는 NFCData 형식
"TNF=0, Payload Type={length = 0, bytes = 0x}, Payload ID={length = 0, bytes = 0x}, Payload={length = 0, bytes = 0x}, ChunkSize=4294967295"

**Comment by bwrw2347** [comment]
2/13~
beacon 구입 및 테스트 중
