### ISSUE TITLE
주문전송시 POS프로그램 알림기능

### ISSUE THREAD

**Issue by tksrl0379** [tksrl0379/OutOfKiosk#18]
POS팀과 DB연동 (테이블 통일 및 PHP서버 수정)
 - 실제로 App에서 서버를 통해 POS 프로그램에 메시지가 전송되는지 확인

**Comment by JacksonPk** [comment]
App에서 DB까지의 전송은 되나, POS 프로그램 구조가 변경되어 추후에 POS프로그래밍 변경 완료 시 확인작업
