### ISSUE TITLE
음성인식 개선을 위한 알고리즘 (유사도 분석 알고리즘)

### ISSUE THREAD

**Issue by JacksonPk** [tksrl0379/OutOfKiosk#19]
STT에서 잘못된 텍스트를 받는 시나리오 개선
 - Bigram을 통해 확률적 유사도를 높이는 알고리즘 방안 제시 및 학습

**Comment by tksrl0379** [comment]
STT엔진이 간간히 사용자의 발화를 제대로 인식하지 못하는 경우가 생김
 - ex) 타로 스무디 -> 바로, 하루 스무디
 - 예시에서 알 수 있다시피 STT엔진에서 오인식하는 경우에도 실제로 의도한 단어와 어느 정도 유사성을 보임. 
 - 따라서 N-gram(bigram) 알고리즘을 이용하여 dialogflow의 entity에 등록된 단어들과 STT엔진이 오인식한 단어를 비교하여 가장 유사한 단어를 추천. 

1. 영어와 달리 한글은 문자 하나에 음소가 2개 이상 들어가므로 문자에 있는 음소를 모두 분해하는 알고리즘이 필요 
: 구현 성공 (php)

2. dialogflow의 entity에 있는 단어 목록을 DB에 등록 - 음소 분해 - 2음소씩 나누어서 db에 등록. 
(타로 -> ^ㅌ, ㅌ ㅏ, ㅏㄹ, ㄹㅗ, ㅗ$  총 5행)
: 구현 성공 (php, mysql)

3. 이를 기반으로 mysql query문을 통해 유사도를 분석
: 구현 성공 (mysql) 및 개선 필요( 알고리즘을 바꿔가면서 추천 성공률이 높도록 여러번 테스트할 필요가 있어보임)

4. 가장 유사도가 높은 entity 단어 1개를 사용자에게 추천
: 구현.
