### ISSUE TITLE
장애인 모바일 APP 접근성 지침

### ISSUE THREAD

**Issue by tksrl0379** [tksrl0379/OutOfKiosk#2]
http://www.wah.or.kr/_Upload/propose/4.%EB%AA%A8%EB%B0%94%EC%9D%BC%EC%95%B1%EC%A0%91%EA%B7%BC%EC%84%B1%EC%A7%80%EC%B9%A8.pdf

http://www.websoul.co.kr/accessibility/PDF/%EB%AA%A8%EB%B0%94%EC%9D%BC%20%EC%95%A0%ED%94%8C%EB%A6%AC%EC%BC%80%EC%9D%B4%EC%85%98%20%EC%A0%91%EA%B7%BC%EC%84%B1%20%EC%A7%80%EC%B9%A8(%EB%AF%B8%EB%9E%98%EC%B0%BD%EC%A1%B0%EA%B3%BC%ED%95%99%EB%B6%80%EA%B3%A0%EC%8B%9C%EC%A0%9C2013-107%ED%98%B8).pdf

**Comment by JacksonPk** [comment]
https://www.youtube.com/watch?v=FLyE4ecUJVY

### 도로 안전시설 설치 및 관리 지침

### 4.6.3. 색상 및 재료
 #### 가. 색상
 - 돌출 부분을 포함한 점자블록 전체의 색상은 원칙적으로 황색을 사용한다. 단,  상황에 따라 주변 바닥재의 색상과 뚜렷하게 대비가 되는 다른 색상을 사용할 수 있다.

----
### 제2장 모바일 애플리케이션 접근성 준수사항
#### 제11조(명도 대비) 화면에 표시되는 모든 정보는 전경색과 배경색이 구분될 수 있도록 최소 대비 이상으로 제공되어야 한다.
- 명도 대비는 화면의 배경색과 객체를 표시하는 데에 사용되는 전경색 사이의 명도 차이의 비율(contrast)을 말한다.
- 고대비 제공이 불가능할 경우, 애플리케이션의 설정 기능에 명도 대비 조절 기능을 제공한다.
- 화면상의 모든 정보의 최소 대비는 3:1 이상이어야 한다. 저시력인, 고령자 등에게 실효성을 가지기 위해서는 명도 대비가 4.5:1 이상이 되는 것이 바람직하다. 단, 사진과 동영상은 예외로 한다.
