### ISSUE TITLE
블루투스 허용 시 음성주문 STT 후 모든 소리가 작아지는 현상

### ISSUE THREAD

**Issue by JacksonPk** [tksrl0379/OutOfKiosk#23]
앱을 종료할 때 까지 소리가 작아짐

-원인- 
Bluetooth 를 사용할 경우 STT기능에서 블루투스 이어폰이 아닌, 스마트폰 자체 내에서 소리가 나는 것을 방지하기위하여 옵션을 설정하여 블루투스이어폰에서 STT기능 및, VoiceOver 소리를 잘 전달하도록 적용시켰으나,
이에 따른 스마트폰에서 STT음성인식 기능 이후에, VoiceOver 및 STT음성 소리가 현저히 작아지는 현상이 발견.

-현재로는 블루투스 옵션기능을 사용하지않고, 추후에 추가하기로 하며, 블루투스 이어폰 없이 STT기능과 VoiceOver 모두 소리가 잘 적응되도록 적용시켜놓았음.

**Comment by tksrl0379** [comment]
보류
