### ISSUE TITLE
Dialogflow V1 -> V2 업데이트 필요(V1이 3월에 만료됨)

### ISSUE THREAD

**Issue by JacksonPk** [tksrl0379/OutOfKiosk#24]
Goolge DialogFlow 베타버젼 V1 -> V2변경에 따른 정책과 기술 사용 방법 변경에 따른 챗봇관련 기술 코드 변경.

**Comment by tksrl0379** [comment]
Dialogflow의 V1 API가 3월경에 만료됨에 따라 V2 API로 옮겨야 함.

V1은 기존의 전통적인 POST HTTP Request 를 이용한 REST API 방식을 사용했는데 
V2부터는 Google Cloud의 json 형식으로 된 인증 key를 사용해야 한다.

json 인증키를 사용해야 함에 따라 Swift에서 직접 HTTP Request 하는 것이 불가능하기 때문에 
Php, nodejs 등을 이용하여 중간 web서버에서 json 인증키를 읽여들어 Dialogflow와 질문/응답 대화를
주고 받는다. 

정리하자면, 기존의 방법(V1)은
Swift <-> Dialogflow 였다면,
새로운 방법(V2)은
End user(Swift) <-> Web server <-> Dialogflow 구조이다. 

1. End user -> Web server : POST request 전송
2. Web server -> Dialogflow : POST request에 담긴 message를 Dialogflow api에 전송(using google dialogflow PHP API)
3. Dialogflow -> Web server: 응답 메시지 전송
4. Web server -> End user: 응답 메시지 전송

End user가 Web server로 요청 메시지를 담은 POST request를 보낸다. Web server는 그 요청 메시지를 포함하여 구글에서 제공하는 Php 전용 Dialogflow api를 통해 Dialogflow에 요청 메시지를 전송한다. Dialogflow가 그에 맞는 응답 메시지를 Web server에게 주면 Web server는 End user 에게 응답 메시지를 전송한다. 

V2 장점:
옮기는데 상당한 시간이 걸렸으나 기능 커스터마이징 및 코드 정리는 더 쉬워졌다.  기존의 V1은 특정 기능이 필요할 때마다 반복해서 API를 Http request해야 해서 Swift 코드가 지저분해질 수 있었는데 V2는 PHP 코드에서 원하는 기능만 따로 뽑아내서 한 번에 출력이 가능해졌다.

또한 보안키를 Web 서버에 저장함으로써 기존의 방식과 달리 보안 키 노출 가능성이 거의 없어져서 Git에 업로드할 시 걱정할 필요가 없어졌다.

**Comment by tksrl0379** [comment]
context 를 다루는 API들이 아직 V1버전이라서 이를 모두 V2로 변경하고 기존에 방치해놨던 버그들을 V2 API를 이용해서 모두 수정함.
1. 대화가 끝나고 Session의 context를 초기화하는 작업을 V1 -> V2로 변경
2. 스무디 혹은 프라푸치노 등의 특정 음식 intents(이하 음식 intents)에 들어간 상태에서 '초콜릿' or '모카'를 말하면 초콜릿 / 모카 같이 중복되는 이름을 가지는 Entity들을 위해 마련해둔 intents(이하 중복 방지 intents)로 들어가는 현상이 계속해서 발생함. 
-> 해결: 중복 방지 intents가 요구하는 input context가 smoothie, frappuccino, starbucks-followup이 있으므로 특정 음식 intents로 들어갈 시 Web server에서 이를 인식하여 동적으로 Session의 starbucks-followup을 삭제하여 
중복 방지 intents로 들어가지 못하게 바꿈.

최종 수정 끝.
