### ISSUE TITLE
포스기에서 푸시 노티피케이션(ASPN) 받기.

### ISSUE THREAD

**Issue by JacksonPk** [tksrl0379/OutOfKiosk#31]
포스기에서 주문한 아이템이 나올시에 스마트폰에 알람이 띄게 하는 기능 구현

기능 구성
- 진동알림/소리알림 등으로 사용자가 주문한 아이템이 나왔다는 것을 알게 해준다.
- IOS에서는 진동/소리 알림 등 커스터마이즈 관련은 모두 서버에서 전송할 때 값을 보내준다.

-To do-

-백그라운드에서 받을때마다 뱃지넘버를 증가시킨다.

-Done-
- 인증서 받아오기
.p12 파일 받는 법 확인하기
현재 ID와 Provisioning 연동이 되어야하는데 오늘은 실패.
내일 다시 도전

- 푸시 알림 권환을 물어보고 승인 될 때마다 Token값이 달라짐.
즉, 앱을 삭제하고 다시 빌드할 때마다 달라지는 Token값을 동적으로 php에 넣어줘야 할듯
setTokenValue.php 파일을 만들고 스위프트는 이 파일과 push 연동.
setTokenValue파일은 pushNotification.php를 fwrite로 토큰 값을 받아온 값으로 변경해주기.
-> 앱을 삭제하고 다시 만들때마다 새 토큰값으로 수정해준다.

백그라운드에서 push Notification hanlder 하기
php파일에서 content-available : True 로 payload 에 담아서 보내야 한다.

기술 구현
 - php서버를 이용해야 할듯.

현재 Pos기 쪽에서 함수실행 시, 여기다 앱에서 push notification을 받도록 설정되었다.

- foreGround에서도 pushNotification이 오면 알람이 뜨게 해줘야 한다. (백그라운드)
 -> alertMsg로 알려줄 수 있다.
해결 -> ForeGround에서 알람이 뜨게 수정했다.

- Push 메시지를 받음에 따라 메시지 이름을 바꿔준다.
-> 특정 alert MSG에 따라 글자 변경.

-notification을 이용해서 push 받자마자 바로 main의 progressTitle_View를 변경하게 하기.
-> notification을 사용해서 해결함.

**Comment by tksrl0379** [comment]
https://g-y-e-o-m.tistory.com/24 참고만.
